services:
  web:
    build: .
    container_name: event_mgmt_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
